version: '3'
services:
    traefik:
        image: traefik:v2.2
        ports:
            - 8082:8082
            - 8080:8080
        volumes:
            - "./docker/traefik/traefik.yml:/traefik.yml:ro"
